### ISSUE TITLE
Micromamba environment caching not working with pip

### ISSUE THREAD

**Issue by NakulK48** [mamba-org/setup-micromamba#195]
With the old provision-with-micromamba action:

<img width="694" alt="image" src="https://github.com/mamba-org/setup-micromamba/assets/6199511/cab17773-5fed-49c8-9547-b9a6e1d8f2fe">

As you can see, `pip` recognises that the environment has been restored, with all of its packages (including those installed via `pip`)

With the new setup-micromamba action:

<img width="608" alt="image" src="https://github.com/mamba-org/setup-micromamba/assets/6199511/95fcea83-d7dc-493b-b405-2f67c36d0ff2">

I can't tell whether this is because it's not caching the pip-installed dependencies at all, or because it's not recognising them in the cache.

**Comment by jonashaag** [comment]
This is by design because we cache the environment before your pip call now.

**Comment by NakulK48** [comment]
What's the reason for that change? It's the `setup-micromamba` step that initializes your Python shell and chooses a directory for libraries to be installed into via `pip`. The created `micromamba` env will have all of your pip dependencies installed inside it.

It sounds like the only way to cache the actual installations would be to delve into the internals, find out where `micromamba` is installing your pip packages, and manually cache that?

**Comment by jonashaag** [comment]
Yes. If you use Conda/Micromamba you're not supposed to have a lot of pip installation. You should install the packages with Conda.

**Comment by pavelzw** [comment]
As Jonas already said, this is by design because with conda environments people tend to alter them after the installation. If we would cache the altered version, you could run into problems with reproducibility.
With caching at the beginning of the action and not in the post step, you always get a clean conda environment, it doesn't matter whether you used caching or not.
If you really want the pip stuff to be cached too, you can disable caching in `setup-micromamba` and have an extra `actions/cache@v4` step before `setup-micromamba` of the env location.
